### ISSUE TITLE
Upgrade Deno-sqlite version

### ISSUE THREAD

**Issue by dyedgreen** [denjucks/dexecutor#3]
Please consider upgrading the SQLite version, see https://github.com/dyedgreen/deno-sqlite/releases

The new version now automatically commits changes to databases to the file-system, and generally is more in-line with how a natively compiled SQLite3 package would function.

**Comment by denjucks** [comment]
Thanks for the suggestion, made some updates and now link to v2.0.0 of sqlite. Great library by the way, thanks for making it!
